openapi: 3.0.0
info:
  description: "A simple Express API"
  title: "Flavor List API"
  version: "1.0.0"
servers:
  - url: http://dev.api.com
  - url: http://prod.api.com
tags:
  - name: Flavor List
components:
  schemas:
    FlavorItemDto:
      type: object
      required:
        - ingredients
        - name
      properties:
        id:
          type: string
        ingredients:
          type: string
        name:
          type: string
      example:
        id: "123"
        ingredients: vanilla, black cherry
        name: black cherry
    FlavorItemCreateDto:
      type: object
      required:
        - ingredients
        - name
      properties:
        ingredients:
          type: string
        name:
          type: string
      example:
        ingredients: egg yolk, bacon, egg, cheese
        name: baconeggncheese
    FlavorItemUpdateDto:
      type: object
      required:
        - ingredients
        - name
      properties:
        ingredients:
          type: string
        name:
          type: string
      example:
        ingredients: honey, egg yolk, coffee soil
        name: budget breakfast
paths:
  /flavor-list:
    get:
      summary: Returns the flavor list
      tags:
        - Flavor List
      responses:
        200:
          description: The flavor list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlavorItemDto"
    post:
      summary: Create a new flavor item
      tags:
        - Flavor List
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlavorItemCreateDto"
      responses:
        200:
          description: The flavor item was successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlavorItemDto"
        500:
          description: Some server error
  /flavor-list/{id}:
    get:
      summary: Get the flavor item by ID
      tags:
        - Flavor List
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: The flavor item description by ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlavorItemDto"
        404:
          description: The flavor item was not found
    patch:
      summary: Update the flavor item by ID
      tags:
        - Flavor List
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlavorItemUpdateDto"
      responses:
        200:
          description: The flavor item was updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlavorItemDto"
        404:
          description: The flavor item was not found
        500:
          description: Some server error
    delete:
      summary: Remove the flavor item by ID
      tags:
        - Flavor List
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: The flavor item was deleted
        404:
          description: The flavor item was not found
